name: Build project and Run Lighthouse CI
on:
  push:
    branches:
      - main
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 使用したい Node.js のバージョンを指定します

      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: bun run build

      - name: Setup Lighthouse CI
        run: bun add -g @lhci/cli@0.13.x

      # - name: Run Lighthouse CI
      #   run: lhci autorun
