name: Build project and Run Lighthouse CI
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: |
          bun run build
          ls ./build
          ls ./build/static
          ls ./build/static/js
          cat ./build/index.html

      - name: Setup Lighthouse CI
        run: bun add -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        run: lhci autorun --url=http://localhost:5173/index.html
